# Inherit sensible Rails rules from rubocop-rails-omakase
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'

Rails:
  Enabled: true

# Keep the config minimal; add targeted overrides only as needed.

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
